language: node_js
node_js:
  - 'stable'
jobs:
  include:
    - stage: test
      name: 'unit tests'
      script:
        - npm i
        - echo 'Testing'
        - npm run test
    - stage: 'deploy_branch'
      name: 'deploy feature envs'
      script:
        - npm run build
        - npm install -g firebase-tools
        - ./before_deploy.sh
        - echo 'Deploying'
        - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
        - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
        - firebase deploy --token "$FIREBASE_TOKEN"
    - stage: deploy
      name: 'deploy to staging'
      if: branch = master
      script:
        - npm install -g firebase-tools
        - echo 'Deploying'
        - firebase deploy --token "$FIREBASE_TOKEN"
stages:
  - name: test
    # require the type to be a PR
    if: type = pull_request
  - name: deploy_branch
    # require the type to be a push
    if: type = push AND branch != master
